###
GET http://localhost:8080/exam/java/add?question="1+1"&answer="2"
###
GET http://localhost:8080/exam/java/add?question="1+2"&answer="3"
###
GET http://localhost:8080/exam/java/add?question="1+3"&answer="4"
###
GET http://localhost:8080/exam/java/add?question="1+4"&answer="5"
###
GET http://localhost:8080/exam/java/add?question="1+5"&answer="6"
###
GET http://localhost:8080/exam/java
###
GET http://localhost:8080/exam/java/remove?question="1+5"&answer="6"
###
GET http://localhost:8080/exam/java
###
GET http://localhost:8080/exam/get/1